import { promises as fs } from 'node:fs';
import path from 'node:path';
import ignore, { type Ignore } from 'ignore';
import type { ScanResult, ScannedFile } from '../types.js';

// Files we always try to include first because they tell the model what the
// project IS before it goes spelunking — manifests, lockfiles only if small,
// and conventional onboarding/contribution docs.
const SEED_FILES = [
  'README.md',
  'README',
  'README.rst',
  'CONTRIBUTING.md',
  'CONTRIBUTING',
  'package.json',
  'pyproject.toml',
  'setup.py',
  'setup.cfg',
  'requirements.txt',
  'Cargo.toml',
  'go.mod',
  'pom.xml',
  'build.gradle',
  'build.gradle.kts',
  'Gemfile',
  'composer.json',
  'tsconfig.json',
  'Makefile',
  'Dockerfile',
  'docker-compose.yml',
  'docker-compose.yaml',
  '.tool-versions',
  '.nvmrc',
];

// Source code extensions worth bundling on the initial pass. The agent can
// always pull in more via the read_file tool.
const SOURCE_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.py',
  '.rs',
  '.go',
  '.java',
  '.kt',
  '.rb',
  '.php',
  '.cs',
  '.swift',
  '.scala',
  '.clj',
  '.ex',
  '.exs',
  '.c',
  '.h',
  '.cc',
  '.cpp',
  '.hpp',
  '.m',
  '.mm',
]);

// Directories we never descend into regardless of .gitignore. These commonly
// contain vendored or generated bytes that drown out the actual source.
const HARD_SKIP_DIRS = new Set([
  '.git',
  'node_modules',
  'vendor',
  'dist',
  'build',
  'out',
  '.next',
  '.nuxt',
  '.turbo',
  '.cache',
  '.venv',
  'venv',
  '__pycache__',
  'target',
  '.gradle',
  '.idea',
  '.vscode',
  'coverage',
]);

export interface ScanOptions {
  /** Per-file max in bytes. Larger files are skipped with a reason. */
  maxFileBytes?: number;
  /** Total bundle budget in bytes. Once hit, no more files are added. */
  maxTotalBytes?: number;
}

const DEFAULT_MAX_FILE_BYTES = 60_000;
const DEFAULT_MAX_TOTAL_BYTES = 250_000;

export async function scanRepo(repoRoot: string, options: ScanOptions = {}): Promise<ScanResult> {
  const maxFileBytes = options.maxFileBytes ?? DEFAULT_MAX_FILE_BYTES;
  const maxTotalBytes = options.maxTotalBytes ?? DEFAULT_MAX_TOTAL_BYTES;

  const absRoot = path.resolve(repoRoot);
  const ig = await loadGitignore(absRoot);

  const topLevelEntries = await fs.readdir(absRoot, { withFileTypes: true });
  const topLevel = topLevelEntries
    .filter((e) => !HARD_SKIP_DIRS.has(e.name))
    .map((e) => (e.isDirectory() ? `${e.name}/` : e.name))
    .sort();

  const files: ScannedFile[] = [];
  const skipped: { path: string; reason: string }[] = [];
  let totalBytes = 0;

  const tryInclude = async (relPath: string): Promise<void> => {
    if (totalBytes >= maxTotalBytes) return;
    const abs = path.join(absRoot, relPath);
    let stat;
    try {
      stat = await fs.stat(abs);
    } catch {
      return;
    }
    if (!stat.isFile()) return;
    if (stat.size > maxFileBytes) {
      skipped.push({ path: relPath, reason: `too large (${stat.size}B > ${maxFileBytes}B)` });
      return;
    }
    if (totalBytes + stat.size > maxTotalBytes) {
      skipped.push({ path: relPath, reason: 'budget exhausted' });
      return;
    }
    const buf = await fs.readFile(abs);
    if (looksBinary(buf)) {
      skipped.push({ path: relPath, reason: 'binary' });
      return;
    }
    const contents = buf.toString('utf8');
    files.push({ path: relPath, contents, bytes: buf.byteLength });
    totalBytes += buf.byteLength;
  };

  for (const seed of SEED_FILES) {
    if (files.some((f) => f.path === seed)) continue;
    await tryInclude(seed);
  }

  for await (const relPath of walk(absRoot, ig)) {
    if (totalBytes >= maxTotalBytes) break;
    if (files.some((f) => f.path === relPath)) continue;
    const ext = path.extname(relPath).toLowerCase();
    if (!SOURCE_EXTENSIONS.has(ext)) continue;
    await tryInclude(relPath);
  }

  return { repoRoot: absRoot, files, topLevel, skipped, totalBytes };
}

async function loadGitignore(repoRoot: string): Promise<Ignore> {
  const ig = ignore();
  ig.add(['.git', 'node_modules', 'dist', 'build']);
  try {
    const gi = await fs.readFile(path.join(repoRoot, '.gitignore'), 'utf8');
    ig.add(gi);
  } catch {
    // no .gitignore — fine
  }
  return ig;
}

async function* walk(absRoot: string, ig: Ignore): AsyncGenerator<string> {
  const queue: string[] = [''];
  while (queue.length > 0) {
    const relDir = queue.shift()!;
    const absDir = path.join(absRoot, relDir);
    let entries;
    try {
      entries = await fs.readdir(absDir, { withFileTypes: true });
    } catch {
      continue;
    }
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const entry of entries) {
      const relPath = relDir ? `${relDir}/${entry.name}` : entry.name;
      if (HARD_SKIP_DIRS.has(entry.name)) continue;
      // ignore() matches dirs with trailing slash to disambiguate
      const checkPath = entry.isDirectory() ? `${relPath}/` : relPath;
      if (ig.ignores(checkPath)) continue;
      if (entry.isDirectory()) {
        queue.push(relPath);
      } else if (entry.isFile()) {
        yield relPath;
      }
    }
  }
}

// Cheap binary heuristic: a NUL byte or >30% non-printable chars in the first
// 4KB means we treat it as binary and skip it.
function looksBinary(buf: Buffer): boolean {
  const sample = buf.subarray(0, Math.min(buf.byteLength, 4096));
  if (sample.includes(0)) return true;
  let nonPrintable = 0;
  for (const byte of sample) {
    if (byte === 9 || byte === 10 || byte === 13) continue;
    if (byte < 32 || byte === 127) nonPrintable++;
  }
  return sample.byteLength > 0 && nonPrintable / sample.byteLength > 0.3;
}
