import type { Section, SectionKey } from '../types.js';
import { REQUIRED_SECTIONS } from '../types.js';

const SECTION_HEADINGS: Record<SectionKey, string> = {
  'how-to-run': 'How to run it',
  'mental-model': 'Mental model',
  modules: 'Modules',
  flows: 'Key flows',
  'where-to-start': 'Where to start',
  gotchas: 'Gotchas',
};

export interface RenderInput {
  /** Display name for the repo (usually the basename of the repo root). */
  repoName: string;
  /** Optional one-line tagline pulled from package.json or README. */
  tagline?: string;
  sections: Section[];
  /** Footer block: how this file was generated, when, with what model. */
  footer: {
    generatedAt: string;
    model: string;
    turns: number;
  };
}

export function renderOnboarding(input: RenderInput): string {
  const submitted = new Map(input.sections.map((s) => [s.key, s.body]));
  const missing = REQUIRED_SECTIONS.filter((k) => !submitted.has(k));

  const lines: string[] = [];
  lines.push(`# Onboarding: ${input.repoName}`);
  lines.push('');
  if (input.tagline && input.tagline.trim().length > 0) {
    lines.push(`> ${input.tagline.trim()}`);
    lines.push('');
  }

  if (missing.length > 0) {
    lines.push(
      `> ⚠ ${missing.length} required section(s) missing from this run: ${missing.join(', ')}. The agent loop exited before submitting them. Re-run \`onboard\` to retry.`,
    );
    lines.push('');
  }

  lines.push(
    'This file was written by [`onboard`](https://github.com/) — a one-shot CLI that reads an unfamiliar repository and produces this document. It is meant for the engineer who *did not* write this code.',
  );
  lines.push('');
  lines.push('## Contents');
  lines.push('');
  for (const key of REQUIRED_SECTIONS) {
    const present = submitted.has(key);
    const anchor = SECTION_HEADINGS[key]
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    lines.push(
      `- [${SECTION_HEADINGS[key]}](#${anchor})${present ? '' : ' _(missing — agent did not submit)_'}`,
    );
  }
  lines.push('');

  for (const key of REQUIRED_SECTIONS) {
    lines.push(`## ${SECTION_HEADINGS[key]}`);
    lines.push('');
    const body = submitted.get(key);
    if (body !== undefined) {
      lines.push(body.trim());
    } else {
      lines.push(`_(missing — onboard's agent loop did not submit this section)_`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    `_Generated by \`onboard\` on ${input.footer.generatedAt} using \`${input.footer.model}\` in ${input.footer.turns} turn${input.footer.turns === 1 ? '' : 's'}. Re-run any time the repo changes — this file is meant to be regenerated, not hand-edited._`,
  );
  lines.push('');

  return lines.join('\n');
}
